// frontend/tutorialScript.js
export const tutorialSteps = {
  'START': {
    speaker: 'Elara',
    text: "Welcome, Commander. To begin, please select our homeworld to view its status.",
    highlightSelector: null,
    trigger: { event: 'GAME_START' },
    next: 'valeriusOpening'
  },
  'valeriusOpening': {
    speaker: 'Valerius',
    text: "Welcome is a luxury we cannot afford. The situation is dire!\n\nThe old Galactic Empire has shattered, and from its ashes, rogue AIs have risen, threatening to consume what little remains. We are all that is left.\n\nWe must consolidate our position, post-haste!",
    highlightSelector: null,
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: 'elaraSpeedControlsIntro' 
},
'elaraSpeedControlsIntro': {
    speaker: 'Elara',
    text: "Commander, time is a resource like any other. You can manipulate the flow of our **Virtual Symmetry System** using these controls.\n\nNote that my and the General's communiques will automatically pause the system to ensure you don't miss critical information.",
    highlightSelector: '#speedPanel',
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: 'homeworldSelected' 
},
  'homeworldSelected': {
    speaker: 'Elara',
    text: "Excellent. This is our resource panel. As you can see, our economy is fragile. Our empire's income is based on two resources: Credits, generated by our population, and Minerals, gathered from mines.\n\nWhile our population will grow on its own, we must personally construct mines to increase our mineral production.",
    highlightSelector: '#resourcePanel',
    trigger: { event: 'STAR_SELECTED', payload: { isPlayerHomeworld: true } },
    next: 'elaraMineRecommendation'
  },
  'elaraMineRecommendation': {
    speaker: 'Elara',
    text: "Therefore, I recommend building a mine to secure our resource flow. General Valerius has other ideas, of course.",
    highlightSelector: '#buildMineButton',
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: 'valeriusOpeningStatement'
  },
  'valeriusOpeningStatement': {
      speaker: 'Valerius',
      text: "An empire without a fleet is merely prey! Our shipyard is operational - build a fighter. And do not forget planetary defenses to protect this asset.",
      highlightSelector: ['#buildFighterButton', '#buildDefenseButton'],
      trigger: { event: 'TUTORIAL_CONTINUE' },
      next: 'firstActionComplete'
  },
'firstActionComplete': {
    speaker: null, 
    text: null,
    highlightSelector: null,
    triggers: [
        {
            trigger: {
                any: [
                    { event: 'COMPLETE_PLANETARY', payload: { type: 'Mine', isPlayerAction: true } },
                    { event: 'COMPLETE_PLANETARY', payload: { type: 'Defense Upgrade', isPlayerAction: true } },
                ]
            },
            action: {
                speaker: 'Elara',
                text: "An excellent first step, Commander. Now that our position is more secure, we should look to the stars and find a nearby neutral planet to expand our influence.",
                highlightSelector: null,
                next: null
            }
        },
    ]
  },

  'infraLevel2Unlocked': {
    speaker: 'Elara',
    text: "Commander! The infrastructure upgrade is complete.\n\nWe can now support a larger population, a total of ten mining complexes, and two planetary defense systems.",
    highlightSelector: null,
    trigger: { 
        event: 'UNLOCK', 
        payload: { option: 'Shipyard Lvl 2' },
        isPlayerAction: true 
    },
    next: 'valeriusInfraComment'
  },

  'valeriusInfraComment': {
    speaker: 'Valerius',
    text: "And more importantly, a higher infrastructure level allows for more advanced shipyards. Stronger ships require a solid foundation.",
    highlightSelector: '#upgradeShipyardButton',
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: null
  },

  'firstConquestComplete': {
    speaker: 'Elara',
    text: "Brilliant, Commander! A new star brings new resources and opportunities.\n\nDeveloping its infrastructure is key: each level increases the maximum population and the number of mines it can support.",
    highlightSelector: '#upgradeInfrastructureButton',
    trigger: { event: 'CONQUEST_COMPLETE', payload: { isPlayerConquest: true } },
    next: null
  },

  'shipyardLevel2Unlocked': {
    speaker: 'Valerius',
    text: "Excellent, Commander. Our new shipyard allows for the construction of Destroyer-class ships!\n\nThey're designed to wreak havoc against enemy fighter squadrons.",
    highlightSelector: '#buildDestroyerButton',
    trigger: { 
        event: 'COMPLETE_PLANETARY', 
        payload: { 
            type: 'Shipyard Lvl 2', 
            isPlayerAction: true 
        } 
    },
    next: null
  },

  'infraLevel3Unlocked': {
    speaker: 'Elara',
    text: "Commander, reaching this infrastructure level is a significant milestone.\n\nOur power grids and industrial fabricators can now support far more complex construction projects than before. This opens up... new possibilities.",
    highlightSelector: null,
    trigger: { 
        event: 'UNLOCK', 
        payload: { 
            option: 'Shipyard Lvl 3',
            isPlayerAction: true 
        } 
    },
    next: 'valeriusCruiserIntro'
},

'valeriusCruiserIntro': {
    speaker: 'Valerius',
    text: "Forget the theories, Economist. A larger industrial base supports a larger shipyard. Simple as that.\n\nCommander, that shipyard upgrade will allow us to construct Capital Ships. True behemoths, capable of taking the fight directly to the AI's most fortified worlds. See to it. Our victory may depend on it.",
    highlightSelector: '#upgradeShipyardButton',
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: null
},

  'infraLevel4Unlocked': {
    speaker: 'Elara',
    text: "Commander! We've made a tremendous scientific breakthrough! We believe we've found a way to harness localized wormhole technology. The work is still theoretical, but the potential is immense.",
    highlightSelector: null,
    trigger: { 
        event: 'UNLOCK', 
        payload: { 
            option: 'Shipyard Lvl 4', // Laukeaa kun tämä tulee mahdolliseksi
            isPlayerAction: true 
        } 
    },
    next: 'valeriusSlipstreamQuery'
},

'valeriusSlipstreamQuery': {
    speaker: 'Valerius',
    text: "Science is meaningless unless it has military applications. Can our forces utilize this 'breakthrough,' Economist?",
    highlightSelector: null,
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: 'elaraSlipstreamReply'
},

'elaraSlipstreamReply': {
    speaker: 'Elara',
    text: "Theoretically, yes. A ship could generate a micro-wormhole to bypass conventional travel limitations. However, the power requirements would be staggering... it would require a shipyard of unprecedented scale.",
    highlightSelector: '#upgradeShipyardButton', // Korostaa päivitysnappia
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: null
},

'infraLevel5Unlocked': {
    speaker: 'Elara',
    text: "A momentous day, Commander! Our scientists have finally stabilized the wormhole technology. By constructing a 'Galactic Hub' on this world, we can create a permanent gateway, forever changing the face of interstellar travel.",
    highlightSelector: '#buildGalacticHubButton',
    trigger: {
      event: 'COMPLETE_PLANETARY',
      payload: {
        type: 'Infrastructure Lvl 5',
        isPlayerAction: true
      }
    },
    next: null
},

'firstHubBuilt': {
    speaker: 'Elara',
    text: "The Hub is operational! Fascinating... the energy draw is so immense that each Hub can only sustain stable connections to the two nearest neighboring Hubs.",
    highlightSelector: null,
    trigger: {
      event: 'COMPLETE_PLANETARY',
      payload: {
        type: 'Galactic Hub',
        isPlayerAction: true
      }
    },
    next: 'valeriusHubStrategy'
},

'valeriusHubStrategy': {
    speaker: 'Valerius',
    text: "Commander, this network is a strategic asset of the highest order. It allows for instant redeployment of our fleets across vast distances. Planning the layout of this network in advance will be paramount to our victory.",
    highlightSelector: null,
    trigger: { event: 'TUTORIAL_CONTINUE' },
    next: null
},

// =======================================================
// ALUSTEN TUTORIAALIVIESTIT (Nämä olivat jo oikein)
// =======================================================

'fleetFormation': {
    speaker: 'Valerius',
    text: "Commander, you now have multiple ships. Time to organize them!\n\n" +
          "**Formation tactics:**\n" +
          "• Hold **SHIFT** and drag to select multiple ships\n" +
          "• Press **CTRL + 1** to assign them to control group 1\n" +
          "• Press **1** to instantly select the group\n" +
          "• Double-tap **1** to focus camera on them\n\n" +
          "Organized fleets are victorious fleets!",
    highlightSelector: null,
    trigger: {
      event: 'PLAYER_HAS_MULTIPLE_SHIPS'
    },
    next: null
},

'firstFighterBuilt': {
    speaker: 'Valerius',
    text: "Excellent! Your first Fighter is ready. These nimble craft are perfect for quick strikes and reconnaissance. Build more to form effective squadrons.\n\nBe careful trying to assault a well defended planet with mere fighters, as any planetary defense system will shred them to pieces...",
    highlightSelector: null,
    trigger: { 
        event: 'SHIP_SPAWNED', 
        payload: { 
            type: 'Fighter', 
            isPlayerAction: true,
            firstOfType: true
        } 
    },
    next: 'valeriusMovementCommands'
},
'valeriusMovementCommands': {
    speaker: 'Valerius',
    text: "To command your forces, select them by **holding the SHIFT key and dragging a selection box** with the left mouse button. Then, **issue a move order with a right-click** on a target star.\n\nOur ships utilize established starlanes for rapid transit. They can traverse the void between unconnected stars, but be warned – such travel is significantly slower.\n\nAnd remember, Commander: we lack faster-than-light communication. Once an order is given, it cannot be recalled. Make your commands with conviction.",
    highlightSelector: null,
    trigger: { event: 'TUTORIAL_CONTINUE' }, 
    next: null 
},

'firstDestroyerBuilt': {
    speaker: 'Valerius',
    text: "A Destroyer! Now we're talking. These warships pack serious firepower and can engage multiple fighters. The backbone of any fleet.\n\nSadly, the heavy firepower comes with a cost: destroyers move slower through the void. Coordinate your fleet's movements carefully, commander.",
    highlightSelector: null,
    trigger: { 
        event: 'SHIP_SPAWNED', 
        payload: { 
            type: 'Destroyer', 
            isPlayerAction: true,
            firstOfType: true
        } 
    },
    next: null
},

'firstCruiserBuilt': {
    speaker: 'Valerius',
    text: "Magnificent! A Cruiser rolls off the assembly line. These capital ships can devastate enemy destroyers and siege heavily defended worlds.\n\nAs with destroyers, cruisers are also slow in the void.\n\nCruisers are extremely vulnurable against fast moving fighter swarms. Consider joining a destroyer squadron with these beasts.",
    highlightSelector: null,
    trigger: { 
        event: 'SHIP_SPAWNED', 
        payload: { 
            type: 'Cruiser', 
            isPlayerAction: true,
            firstOfType: true
        } 
    },
    next: null
},

'firstSlipstreamBuilt': {
    speaker: 'Elara',
    text: "Fascinating! The Slipstream Frigate uses advanced propulsion technology. Its speed advantage can turn the tide of battle - use it wisely!",
    highlightSelector: null,
    trigger: { 
        event: 'SHIP_SPAWNED', 
        payload: { 
            type: 'Slipstream Frigate', 
            isPlayerAction: true,
            firstOfType: true
        } 
    },
    next: null
  },

  
};